
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"/home/myagmartseren/Documents/school/pre_desktop/build/assets/frame3")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1354x676")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 676,
    width = 1354,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    56.0,
    162.0,
    1496.0,
    1184.0,
    fill="#F5F5F5",
    outline="")

canvas.create_rectangle(
    0.0,
    0.0,
    574.35986328125,
    676.0,
    fill="#D4F1F4",
    outline="")

canvas.create_text(
    694.0,
    122.0,
    anchor="nw",
    text="Бүртгүүлэх",
    fill="#003B73",
    font=("Inter SemiBold", 19 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    804.5,
    211.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=697.5299999713898,
    y=195.0,
    width=213.94000005722046,
    height=30.0
)

canvas.create_text(
    694.0,
    180.0,
    anchor="nw",
    text="Овог",
    fill="#189AB4",
    font=("Inter SemiBold", 9 * -1)
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    804.5,
    331.0,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=697.5299999713898,
    y=315.0,
    width=213.94000005722046,
    height=30.0
)

canvas.create_text(
    694.0,
    295.0,
    anchor="nw",
    text="Имэйл хаяг",
    fill="#189AB4",
    font=("Inter SemiBold", 9 * -1)
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    803.5,
    388.0,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=696.5299999713898,
    y=372.0,
    width=213.94000005722046,
    height=30.0
)

canvas.create_text(
    695.0,
    354.0,
    anchor="nw",
    text="Нууц үг",
    fill="#189AB4",
    font=("Inter SemiBold", 9 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=695.0,
    y=501.0,
    width=221.0,
    height=32.0
)

entry_image_4 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
entry_bg_4 = canvas.create_image(
    1080.5,
    388.0,
    image=entry_image_4
)
entry_4 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_4.place(
    x=973.5299999713898,
    y=372.0,
    width=213.94000005722046,
    height=30.0
)

entry_image_5 = PhotoImage(
    file=relative_to_assets("entry_5.png"))
entry_bg_5 = canvas.create_image(
    804.5,
    271.0,
    image=entry_image_5
)
entry_5 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_5.place(
    x=697.5299999713898,
    y=255.0,
    width=213.94000005722046,
    height=30.0
)

canvas.create_text(
    695.0,
    236.0,
    anchor="nw",
    text="Хэрэглэгчийн нэр",
    fill="#189AB4",
    font=("Inter SemiBold", 9 * -1)
)

canvas.create_text(
    970.0,
    354.0,
    anchor="nw",
    text="Нууц үгээ баталгаажуулах",
    fill="#189AB4",
    font=("Inter SemiBold", 9 * -1)
)

entry_image_6 = PhotoImage(
    file=relative_to_assets("entry_6.png"))
entry_bg_6 = canvas.create_image(
    1080.5,
    211.0,
    image=entry_image_6
)
entry_6 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_6.place(
    x=973.5299999713898,
    y=195.0,
    width=213.94000005722046,
    height=30.0
)

canvas.create_text(
    970.0,
    178.0,
    anchor="nw",
    text="Нэр ",
    fill="#189AB4",
    font=("Inter SemiBold", 9 * -1)
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=693.0,
    y=413.0,
    width=186.0,
    height=14.0
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    740.0,
    63.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    287.0,
    338.0,
    image=image_image_2
)
window.resizable(False, False)
window.mainloop()
